/**
 * USA Cities Collection
 * Top 200 largest cities in the United States with population data
 */

export interface USACity {
    city: string;
    state: string;
    population: number;
}

export const USA_CITIES: USACity[] = [
    { city: "New York", state: "New York", population: 8258035 },
    { city: "Los Angeles", state: "California", population: 3820914 },
    { city: "Chicago", state: "Illinois", population: 2664452 },
    { city: "Houston", state: "Texas", population: 2304580 },
    { city: "Phoenix", state: "Arizona", population: 1700000 },
    { city: "Philadelphia", state: "Pennsylvania", population: 1567442 },
    { city: "San Antonio", state: "Texas", population: 1500000 },
    { city: "San Diego", state: "California", population: 1394928 },
    { city: "Dallas", state: "Texas", population: 1300092 },
    { city: "San Jose", state: "California", population: 1026908 },
    { city: "Austin", state: "Texas", population: 980000 },
    { city: "Jacksonville", state: "Florida", population: 870000 },
    { city: "Fort Worth", state: "Texas", population: 880000 },
    { city: "Columbus", state: "Ohio", population: 850106 },
    { city: "Indianapolis", state: "Indiana", population: 829718 },
    { city: "Charlotte", state: "North Carolina", population: 827097 },
    { city: "San Francisco", state: "California", population: 864816 },
    { city: "Seattle", state: "Washington", population: 684451 },
    { city: "Denver", state: "Colorado", population: 682545 },
    { city: "Washington", state: "District of Columbia", population: 601723 },
    { city: "Boston", state: "Massachusetts", population: 667137 },
    { city: "El Paso", state: "Texas", population: 681124 },
    { city: "Nashville", state: "Tennessee", population: 530852 },
    { city: "Detroit", state: "Michigan", population: 677116 },
    { city: "Oklahoma City", state: "Oklahoma", population: 631346 },
    { city: "Portland", state: "Oregon", population: 632309 },
    { city: "Las Vegas", state: "Nevada", population: 623747 },
    { city: "Memphis", state: "Tennessee", population: 655770 },
    { city: "Louisville", state: "Kentucky", population: 643000 },
    { city: "Baltimore", state: "Maryland", population: 621849 },
    { city: "Milwaukee", state: "Wisconsin", population: 600155 },
    { city: "Albuquerque", state: "New Mexico", population: 559121 },
    { city: "Tucson", state: "Arizona", population: 531641 },
    { city: "Fresno", state: "California", population: 520052 },
    { city: "Mesa", state: "Arizona", population: 471825 },
    { city: "Sacramento", state: "California", population: 490712 },
    { city: "Atlanta", state: "Georgia", population: 463878 },
    { city: "Kansas City", state: "Missouri", population: 475378 },
    { city: "Colorado Springs", state: "Colorado", population: 456568 },
    { city: "Omaha", state: "Nebraska", population: 443885 },
    { city: "Raleigh", state: "North Carolina", population: 451066 },
    { city: "Miami", state: "Florida", population: 441003 },
    { city: "Long Beach", state: "California", population: 474140 },
    { city: "Virginia Beach", state: "Virginia", population: 452745 },
    { city: "Oakland", state: "California", population: 419267 },
    { city: "Minneapolis", state: "Minnesota", population: 410939 },
    { city: "Tulsa", state: "Oklahoma", population: 403505 },
    { city: "Tampa", state: "Florida", population: 369075 },
    { city: "Arlington", state: "Texas", population: 388125 },
    { city: "New Orleans", state: "Louisiana", population: 389617 },
    { city: "Wichita", state: "Kansas", population: 389965 },
    { city: "Bakersfield", state: "California", population: 373640 },
    { city: "Cleveland", state: "Ohio", population: 388072 },
    { city: "Aurora", state: "Colorado", population: 359407 },
    { city: "Anaheim", state: "California", population: 350742 },
    { city: "Honolulu", state: "Hawaii", population: 371657 },
    { city: "Santa Ana", state: "California", population: 335400 },
    { city: "Riverside", state: "California", population: 322424 },
    { city: "Corpus Christi", state: "Texas", population: 324074 },
    { city: "Lexington", state: "Kentucky", population: 314488 },
    { city: "Henderson", state: "Nevada", population: 285667 },
    { city: "Stockton", state: "California", population: 305658 },
    { city: "Saint Paul", state: "Minnesota", population: 285068 },
    { city: "Cincinnati", state: "Ohio", population: 296943 },
    { city: "St. Louis", state: "Missouri", population: 315685 },
    { city: "Pittsburgh", state: "Pennsylvania", population: 304391 },
    { city: "Greensboro", state: "North Carolina", population: 285342 },
    { city: "Lincoln", state: "Nebraska", population: 277348 },
    { city: "Anchorage", state: "Alaska", population: 298695 },
    { city: "Plano", state: "Texas", population: 283558 },
    { city: "Orlando", state: "Florida", population: 270934 },
    { city: "Irvine", state: "California", population: 256927 },
    { city: "Newark", state: "New Jersey", population: 281944 },
    { city: "Toledo", state: "Ohio", population: 279789 },
    { city: "Durham", state: "North Carolina", population: 257636 },
    { city: "Chula Vista", state: "California", population: 265757 },
    { city: "Fort Wayne", state: "Indiana", population: 260326 },
    { city: "Jersey City", state: "New Jersey", population: 264290 },
    { city: "St. Petersburg", state: "Florida", population: 257083 },
    { city: "Laredo", state: "Texas", population: 255473 },
    { city: "Madison", state: "Wisconsin", population: 248951 },
    { city: "Chandler", state: "Arizona", population: 260828 },
    { city: "Buffalo", state: "New York", population: 276146 },
    { city: "Lubbock", state: "Texas", population: 279104 },
    { city: "Scottsdale", state: "Arizona", population: 240000 },
    { city: "Reno", state: "Nevada", population: 241445 },
    { city: "Glendale", state: "Arizona", population: 240126 },
    { city: "North Las Vegas", state: "Nevada", population: 260000 },
    { city: "Winston-Salem", state: "North Carolina", population: 241218 },
    { city: "Chesapeake", state: "Virginia", population: 240000 },
    { city: "Norfolk", state: "Virginia", population: 246393 },
    { city: "Fremont", state: "California", population: 235000 },
    { city: "Garland", state: "Texas", population: 235000 },
    { city: "Irving", state: "Texas", population: 240000 },
    { city: "Hialeah", state: "Florida", population: 237069 },
    { city: "Richmond", state: "Virginia", population: 230000 },
    { city: "Boise", state: "Idaho", population: 230000 },
    { city: "Spokane", state: "Washington", population: 231311 },
    { city: "Baton Rouge", state: "Louisiana", population: 220000 },
    { city: "Tacoma", state: "Washington", population: 220000 },
    { city: "San Bernardino", state: "California", population: 220000 },
    { city: "Modesto", state: "California", population: 220000 },
    { city: "Fontana", state: "California", population: 220000 },
    { city: "Des Moines", state: "Iowa", population: 215000 },
    { city: "Oxnard", state: "California", population: 210000 },
    { city: "Montgomery", state: "Alabama", population: 200000 },
    { city: "Moreno Valley", state: "California", population: 210000 },
    { city: "Shreveport", state: "Louisiana", population: 190000 },
    { city: "Aurora", state: "Illinois", population: 200000 },
    { city: "Yonkers", state: "New York", population: 200000 },
    { city: "Akron", state: "Ohio", population: 195000 },
    { city: "Huntington Beach", state: "California", population: 195000 },
    { city: "Little Rock", state: "Arkansas", population: 195000 },
    { city: "Augusta", state: "Georgia", population: 196000 },
    { city: "Amarillo", state: "Texas", population: 200000 },
    { city: "Glendale", state: "California", population: 190000 },
    { city: "Mobile", state: "Alabama", population: 198806 },
    { city: "Grand Rapids", state: "Michigan", population: 190000 },
    { city: "Salt Lake City", state: "Utah", population: 200000 },
    { city: "Tallahassee", state: "Florida", population: 190000 },
    { city: "Huntsville", state: "Alabama", population: 200000 },
    { city: "Grand Prairie", state: "Texas", population: 190000 },
    { city: "Knoxville", state: "Tennessee", population: 190000 },
    { city: "Worcester", state: "Massachusetts", population: 190000 },
    { city: "Newport News", state: "Virginia", population: 185000 },
    { city: "Brownsville", state: "Texas", population: 185000 },
    { city: "Overland Park", state: "Kansas", population: 190000 },
    { city: "Santa Clarita", state: "California", population: 180000 },
    { city: "Providence", state: "Rhode Island", population: 196657 },
    { city: "Garden Grove", state: "California", population: 175000 },
    { city: "Chattanooga", state: "Tennessee", population: 180000 },
    { city: "Oceanside", state: "California", population: 175000 },
    { city: "Jackson", state: "Mississippi", population: 135671 },
    { city: "Fort Lauderdale", state: "Florida", population: 170000 },
    { city: "Santa Rosa", state: "California", population: 175000 },
    { city: "Rancho Cucamonga", state: "California", population: 175000 },
    { city: "Port St. Lucie", state: "Florida", population: 200000 },
    { city: "Tempe", state: "Arizona", population: 180000 },
    { city: "Ontario", state: "California", population: 180000 },
    { city: "Vancouver", state: "Washington", population: 180000 },
    { city: "Sioux Falls", state: "South Dakota", population: 180000 },
    { city: "Peoria", state: "Arizona", population: 175000 },
    { city: "Springfield", state: "Missouri", population: 170000 },
    { city: "Pembroke Pines", state: "Florida", population: 170000 },
    { city: "Elk Grove", state: "California", population: 175000 },
    { city: "Salem", state: "Oregon", population: 175000 },
    { city: "Corona", state: "California", population: 170000 },
    { city: "Eugene", state: "Oregon", population: 175000 },
    { city: "McKinney", state: "Texas", population: 180000 },
    { city: "Fort Collins", state: "Colorado", population: 170000 },
    { city: "Lancaster", state: "California", population: 170000 },
    { city: "Cary", state: "North Carolina", population: 170000 },
    { city: "Palmdale", state: "California", population: 160000 },
    { city: "Hayward", state: "California", population: 160000 },
    { city: "Salinas", state: "California", population: 160000 },
    { city: "Frisco", state: "Texas", population: 165000 },
    { city: "Springfield", state: "Massachusetts", population: 160000 },
    { city: "Pasadena", state: "Texas", population: 160000 },
    { city: "Macon", state: "Georgia", population: 155000 },
    { city: "Alexandria", state: "Virginia", population: 155000 },
    { city: "Pomona", state: "California", population: 146416 },
    { city: "Lakewood", state: "Colorado", population: 150000 },
    { city: "Sunnyvale", state: "California", population: 150000 },
    { city: "Escondido", state: "California", population: 150000 },
    { city: "Kansas City", state: "Kansas", population: 150000 },
    { city: "Hollywood", state: "Florida", population: 150000 },
    { city: "Clarksville", state: "Tennessee", population: 150000 },
    { city: "Rockford", state: "Illinois", population: 145000 },
    { city: "Torrance", state: "California", population: 145000 },
    { city: "Joliet", state: "Illinois", population: 152579 },
    { city: "Paterson", state: "New Jersey", population: 145000 },
    { city: "Bridgeport", state: "Connecticut", population: 145000 },
    { city: "Naperville", state: "Illinois", population: 145000 },
    { city: "Mesquite", state: "Texas", population: 145000 },
    { city: "Savannah", state: "Georgia", population: 145000 },
    { city: "Syracuse", state: "New York", population: 145678 },
    { city: "Dayton", state: "Ohio", population: 140000 },
    { city: "Pasadena", state: "California", population: 140000 },
    { city: "Orange", state: "California", population: 140000 },
    { city: "Fullerton", state: "California", population: 140000 },
    { city: "Killeen", state: "Texas", population: 140000 },
    { city: "Hampton", state: "Virginia", population: 135000 },
    { city: "McAllen", state: "Texas", population: 151972 },
    { city: "Warren", state: "Michigan", population: 135000 },
    { city: "Bellevue", state: "Washington", population: 150000 },
    { city: "Miramar", state: "Florida", population: 140000 },
    { city: "West Valley City", state: "Utah", population: 135000 },
    { city: "Midland", state: "Texas", population: 135000 },
    { city: "Columbia", state: "South Carolina", population: 135000 },
    { city: "Sterling Heights", state: "Michigan", population: 134456 },
    { city: "Gainesville", state: "Florida", population: 151942 },
    { city: "Cedar Rapids", state: "Iowa", population: 135000 },
    { city: "Visalia", state: "California", population: 135000 },
    { city: "Coral Springs", state: "Florida", population: 135000 },
    { city: "New Haven", state: "Connecticut", population: 130000 },
    { city: "Stamford", state: "Connecticut", population: 130000 },
    { city: "Thousand Oaks", state: "California", population: 130000 },
    { city: "Concord", state: "California", population: 130000 },
    { city: "Elizabeth", state: "New Jersey", population: 130000 },
    { city: "Murfreesboro", state: "Tennessee", population: 130000 },
];

/**
 * Get unique city names (for simple city list without duplicates)
 */
export function getUSACityNames(): string[] {
    const uniqueCities = new Set(USA_CITIES.map(c => c.city));
    return Array.from(uniqueCities);
}

/**
 * Get cities by state
 */
export function getCitiesByState(state: string): USACity[] {
    return USA_CITIES.filter(c => c.state === state);
}

/**
 * Find city by name and state (for upsert operations)
 */
export function findCity(city: string, state: string): USACity | undefined {
    return USA_CITIES.find(c => c.city === city && c.state === state);
}

/**
 * Get top N cities by population
 */
export function getTopCities(n: number): USACity[] {
    return [...USA_CITIES].sort((a, b) => b.population - a.population).slice(0, n);
}
